(function (root) {
  // Keys = merchantKey() (accents/spaces/Nouveau stripped). Values = explicit hosts.
  const MERCHANT_DOMAINS = {
    auchan: ["auchan.fr"],
    carrefour: ["carrefour.fr"],
    deliveroo: ["deliveroo.fr", "deliveroo.com"],
    hellofresh: ["hellofresh.fr"],
    magasinsu: ["coursesu.com", "magasins-u.com", "systeme-u.fr"],
    monoprix: ["monoprix.fr"],
    nespresso: ["nespresso.com"],
    thefork: ["thefork.fr"],
    ubereats: ["ubereats.com"],
    uberone: ["uber.com"],
    ubervtc: ["uber.com"],
    apple: ["apple.com"],
    bosch: ["bosch.fr", "bosch-home.fr"],
    cdiscount: ["cdiscount.com"],
    darty: ["darty.com"],
    fnac: ["fnac.com"],
    hp: ["hp.com"],
    philips: ["philips.fr"],
    philipshue: ["philips-hue.com", "philips.fr"],
    samsung: ["samsung.com"],
    samsungmaison: ["samsung.com"],
    samsungwatch: ["samsung.com"],
    samsunggaming: ["samsung.com"],
    siemens: ["siemens-home.bsh-group.com", "siemens.com"],
    asos: ["asos.com", "asos.fr"],
    bonobo: ["bonobo.com"],
    boohooman: ["boohooman.com"],
    breal: ["breal.fr"],
    ca: ["c-and-a.com"],
    cachecache: ["cache-cache.fr"],
    converse: ["converse.com"],
    cyrillus: ["cyrillus.fr"],
    eram: ["eram.fr"],
    etam: ["etam.com"],
    galerieslafayette: ["galerieslafayette.com"],
    gemo: ["gemo.fr"],
    hm: ["hm.com"],
    laredoute: ["laredoute.fr"],
    marionnaud: ["marionnaud.fr"],
    primark: ["primark.com"],
    rituals: ["rituals.com"],
    sarenza: ["sarenza.com"],
    showroomprive: ["showroomprive.com"],
    spartoo: ["spartoo.com"],
    swarovski: ["swarovski.com"],
    yvesrocher: ["yves-rocher.fr"],
    zalando: ["zalando.fr"],
    zalandosport: ["zalando.fr"],
    alinea: ["alinea.com"],
    alpiq: ["alpiq.com"],
    ampm: ["ampm.fr"],
    bricocash: ["bricocash.fr"],
    bricomarche: ["bricomarche.com"],
    bricorama: ["bricorama.fr"],
    but: ["but.fr"],
    castorama: ["castorama.fr"],
    conforama: ["conforama.fr"],
    ikea: ["ikea.com"],
    interflora: ["interflora.fr"],
    jardiland: ["jardiland.com"],
    leroymerlin: ["leroymerlin.fr"],
    maisonsdumonde: ["maisonsdumonde.com"],
    naturedecouvertes: ["natureetdecouvertes.com"],
    selency: ["selency.fr"],
    truffaut: ["truffaut.com"],
    verisure: ["verisure.fr"],
    adidas: ["adidas.fr"],
    decathlon: ["decathlon.fr"],
    garmin: ["garmin.com"],
    irun: ["i-run.fr"],
    keepcool: ["keepcool.fr"],
    nike: ["nike.com"],
    strava: ["strava.com"],
    abritel: ["abritel.fr"],
    azureva: ["azureva-vacances.com"],
    belambra: ["belambra.com"],
    campingandco: ["campingandco.com"],
    centerparcs: ["centerparcs.fr"],
    ector: ["ector.fr"],
    europcar: ["europcar.fr"],
    expedia: ["expedia.fr"],
    flixbus: ["flixbus.fr"],
    fram: ["fram.fr"],
    hotelscom: ["hotels.com"],
    jettours: ["jettours.com"],
    lastminutecom: ["lastminute.com"],
    misterfly: ["misterfly.com"],
    mmv: ["mmv.fr"],
    mondialtourisme: ["mondialtourisme.fr"],
    netski: ["netski.com"],
    odalys: ["odalys-vacances.com"],
    ovoyages: ["ovoyages.com"],
    promosejours: ["promosejours.com"],
    promovacances: ["promovacances.com"],
    vtf: ["vtf-vacances.fr"],
    vvf: ["vvf.fr"],
    vvfvillages: ["vvf.fr"],
    nintendo: ["nintendo.com"],
    nintendoeshopcard: ["nintendo.com"],
    pathe: ["pathe.fr"],
    ugc: ["ugc.fr"],
    mk2: ["mk2.com"],
    kinepolis: ["kinepolis.fr"],
    cgrcinemas: ["cgrcinemas.fr"],
    cultura: ["cultura.com"],
    deezer: ["deezer.com"],
    deezerpremium: ["deezer.com"],
    googleplay: ["play.google.com"],
    spotify: ["spotify.com"],
    steam: ["store.steampowered.com", "steampowered.com"],
    xbox: ["xbox.com"],
    wonderbox: ["wonderbox.fr"],
    sonyplaystationstore: ["store.playstation.com", "playstation.com"],
    parcasterix: ["parcasterix.fr"],
    vulcania: ["vulcania.com"],
    nausicaa: ["nausicaa.fr"],
    oceanopolis: ["oceanopolis.com"],
    aubert: ["aubert.com"],
    dupareilaumeme: ["dpam.com"],
    jacadi: ["jacadi.fr"],
    kingjouet: ["king-jouet.com"],
    lagranderecre: ["lagranderecre.fr"],
    natalys: ["natalys.com"],
    okaidi: ["okaidi.fr"],
    orchestra: ["orchestra.fr"],
    oxybul: ["oxybul.com"],
    petitbateau: ["petit-bateau.fr"],
    sergentmajor: ["sergent-major.com"],
    vertbaudet: ["vertbaudet.fr"],
    babbel: ["babbel.com"],
    cafeyn: ["cafeyn.co"],
    lg: ["lg.com"],
    lenovo: ["lenovo.com"],
    dyson: ["dyson.fr"],
    delonghi: ["delonghi.com"],
    tefal: ["tefal.fr"],
    rowenta: ["rowenta.fr"],
    calor: ["calor.fr"],
    moulinex: ["moulinex.fr"],
    sony: ["sony.fr"],
    krups: ["krups.fr"],
    braun: ["braun.fr"],
    kenwood: ["kenwood.fr"],
    dell: ["dell.com"],
    jbl: ["jbl.com"],
    nikon: ["nikon.fr"],
    karcher: ["kaercher.com"],
    whirlpool: ["whirlpool.fr"],
    pierrevacances: ["pierre-vacances.fr"],
    homair: ["homair.com"],
    maeva: ["maeva.com"],
    ucpa: ["ucpa.com"],
    kombo: ["kombo.co"],
    msccroisieres: ["msccroisieres.fr"],
    costacroisieres: ["costacroisieres.fr"],
    croisieurope: ["croisieurope.fr"],
    qpark: ["q-park.fr"],
    euromaster: ["euromaster.fr"],
    autosur: ["autosur.fr"],
    eplaque: ["eplaque.fr"],
    eplaqueimmatriculation: ["eplaque.fr"],
    opodo: ["opodo.fr"],
    edreams: ["edreams.fr"],
    govoyages: ["govoyages.com"],
    campingscom: ["campings.com"],
    adagio: ["adagio-city.com"],
    weekendesk: ["weekendesk.fr"],
    lepermislibrecode: ["lepermislibre.fr"],
    lepermislibrecodeexamen: ["lepermislibre.fr"],
    lepermislibrepermis: ["lepermislibre.fr"],
    lepermislibre: ["lepermislibre.fr"],
    upway: ["upway.fr"],
    intersportski: ["intersport.fr"],
    skiset: ["skiset.com"],
    skimium: ["skimium.com"],
    labelemmaus: ["label-emmaus.co"],
    leslipfrancais: ["leslipfrancais.fr"],
    recyclivre: ["recyclivre.com"],
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = MERCHANT_DOMAINS;
  }
  root.MerchantDomains = MERCHANT_DOMAINS;
})(typeof globalThis !== "undefined" ? globalThis : this);
